import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const myFont = localFont({
  src: '../fonts/DanaVF.woff2',
  variable: '--font-dana',
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir='rtl' lang='fa' className={`${myFont.variable} font-sans`}>
      <body>
        {children}
        <div dir='ltr'>
          <Toaster position='bottom-center' />
        </div>
      </body>
    </html>
  );
}
